// TRY - CATCH


const num1 = 5;

const num3 = 7;

console.log(num1);

try {
    console.log(num2);
} catch (error) {
    console.log(error)
}



console.log(num3);